#!/bin/bash
ssh mkerr@vlite-difx1 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx2 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx3 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx4 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx5 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx6 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx7 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx8 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx9 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx10 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx11 "${1}" < /dev/null &> /dev/null
ssh mkerr@vlite-difx12 "${1}" < /dev/null &> /dev/null
