#!/bin/bash
PACKAGE_DIR=/home/vlite-master/mtk
/mnt/ssd/bin/dada_db -k ${1} -d
#  if [ $? -ne 0 ]
#  then
#    echo "failed to delete old buffer"
#    exit 1
#  fi
/mnt/ssd/bin/dada_db -k ${1} -l 10485760 8
