#!/bin/bash
PACKAGE_DIR=/home/vlite-master/mtk
# first, attempt to scrub the buffer
${PACKAGE_DIR}/bin/dada_dbscrubber -k ${1}
if [ $? -ne 0 ]
then
  echo "dada_dbscrubber unsuccessful, attemping to re-allocate buffer"
  /mnt/ssd/bin/dada_db -k ${1} -d
  if [ $? -ne 0 ]
  then
    echo "failed to delete old buffer"
    exit 1
  fi
  /mnt/ssd/bin/dada_db -k ${1} -l 10485760 8
  if [ $? -ne 0 ]
  then
    echo "failed to create new buffer"
    exit 2
  fi
  # successful, but signal that a new buffer was created so that
  # we can re-connect as needed
  exit 3
fi
echo "buffer scrub was successful"
exit 0
