#!/bin/bash
set -x
# arguments should be
# $1 = reader port
# $2 = baseband dada key 
# $3 = filterbank dada key 
# $4 = write_fb
# $5 = nbit
if [ ${3} -gt 0 ]
then
#/home/vlite-master/mtk/scripts/start_dada ${3} 2012800 8
#/home/vlite-master/mtk/scripts/start_dada $(( ${3} + 2 )) 2012800 8
/home/vlite-master/mtk/scripts/start_dada ${3} 10485760 8
/home/vlite-master/mtk/scripts/start_dada $(( ${3} + 2 )) 10485760 8
fi
gdb -ex=r --args /home/vlite-master/mtk/src/process_baseband -p ${1} -k ${2} -K ${3} -w ${4} -b ${5} -o
if [ ${3} -gt 0 ]
then
wait $(pgrep heimdall)
sleep 1
sudo /home/vlite-master/mtk/bin/dada_db -k ${3} -d
sudo /home/vlite-master/mtk/bin/dada_db -k $(( ${3} + 2 )) -d
fi
