#!/bin/bash
# mapping of arguments is directory from configurations file
# $1 = hostname
# $2 = interface
# $3 = gpu device id
# $4 = reader port
# $5 = writer port
# $6 = info port
# $7 = baseband dada key 
# $8 = filterbank dada key 
# $9 = coadder dada key
# $10 = write_fb
# $11 = nbit
#set -x
PACKAGE_DIR=/home/vlite-master/surya
CUDA_DIR=/usr/cuda-9.2.88
export LD_LIBRARY_PATH=${PACKAGE_DIR}/lib:${CUDA_DIR}/lib64:${LD_LIBRARY_PATH}
#sleep 0.5


# arguments should be
# $1 = interface
# $2 = writer port
# $3 = info port
# $4 = baseband dada key
#sudo -b /home/vlite-master/mtk/scripts/start_writer ${2} ${5} ${6} ${7}
#sudo -b LD_LIBRARY_PATH=${PACKAGE_DIR}/lib ${PACKAGE_DIR}/vlite-fast/scripts/start_writer ${2} ${5} ${6} ${7}
${PACKAGE_DIR}/vlite-fast/scripts/start_writer ${2} ${5} ${6} ${7} &
sleep 0.5

# $1 = reader port
# $2 = baseband dada key 
# $3 = filterbank dada key 
# $4 = coadder dada key
# $5 = write_fb
# $6 = nbit
# $7 = gpu_id
#sudo LD_LIBRARY_PATH=${LD_LIBRARY_PATH} -b /home/vlite-master/mtk/scripts/start_process ${4} ${7} ${8} ${9} ${10}
${PACKAGE_DIR}/vlite-fast/scripts/start_process ${4} ${7} ${8} ${9} ${10} ${11} ${3}&
