#!/bin/bash
# mapping of arguments is directory from configurations file
# $1 = hostname
# $2 = interface
# $3 = gpu device id
# $4 = reader port
# $5 = writer port
# $6 = info port
# $7 = baseband dada key 
# $8 = filterbank dada key 
# $9 = write_fb
# $10 = nbit
set -x
export LD_LIBRARY_PATH=/home/vlite-master/mtk/lib:/usr/cuda/lib64:${LD_LIBRARY_PATH}
#sleep 0.5

# arguments should be
# $1 = interface
# $2 = writer port
# $3 = info port
# $4 = baseband dada key
sudo -b LD_LIBRARY_PATH=${LD_LIBRARY_PATH} /home/vlite-master/mtk/scripts/start_writer ${2} ${5} ${6} ${7}
sleep 0.5

# $1 = reader port
# $2 = baseband dada key 
# $3 = filterbank dada key 
# $4 = write_fb
# $5 = nbit
/home/vlite-master/mtk/scripts/start_process_debug ${4} ${7} ${8} ${9} ${10}
