#!/bin/bash
PACKAGE_DIR=/home/vlite-master/mtk
set -x
# arguments should be
# $1 = reader port
# $2 = baseband dada key 
# $3 = filterbank dada key 
# $4 = write_fb
# $5 = nbit
# $6 = gpu_id
if [ ${3} -gt 0 ]
then
#/home/vlite-master/mtk/scripts/start_dada ${3} 2012800 8
#/home/vlite-master/mtk/scripts/start_dada $(( ${3} + 2 )) 2012800 8
${PACKAGE_DIR}/vlite-fast/scripts/start_dada ${3} 10485760 8
${PACKAGE_DIR}/vlite-fast/scripts/start_dada $(( ${3} + 2 )) 10485760 8
fi

# start nvidia-smi logging if not already
# MTK 12/17/2018 -- disable nvidia-smi logging for now
#if [ ! $(pgrep -x nvidia-smi) ]
#then
#  nvidia-smi -f ${PACKAGE_DIR}/logs/nvidia-smi_log_$(hostname).asc -l 2 &
#  NVIDIA_SMI_PID=$!
#else
#  NVIDIA_SMI_PID=0
#fi
#echo "NVIDIA_SMI_PID=${NVIDIA_SMI_PID}"

# "i" is inject FRB
${PACKAGE_DIR}/bin/process_baseband -k ${2} -K ${3} -w ${4} -b ${5} -g ${6} -o -i
# this will only write kurtosis
#${PACKAGE_DIR}/bin/process_baseband -k ${2} -K ${3} -w ${4} -b ${5} -g ${6} -o -r 1
# this will write both
#${PACKAGE_DIR}/bin/process_baseband -k ${2} -K ${3} -w ${4} -b ${5} -g ${6} -o 
if [ ${3} -gt 0 ]
then
  if [ pgrep -x heimdall > /dev/null ]
  then
    wait $(pgrep -x heimdall)
  fi
sleep 1
#sudo ${PACKAGE_DIR}/bin/dada_db -k ${3} -d
#sudo ${PACKAGE_DIR}/bin/dada_db -k $(( ${3} + 2 )) -d
/mnt/ssd/bin/dada_db -k ${3} -d
/mnt/ssd/bin/dada_db -k $(( ${3} + 2 )) -d
fi

#if [ $NVIDIA_SMI_PID -gt 0 ]
#then
#  kill $NVIDIA_SMI_PID
#fi
