#!/bin/bash
#set -x
# run as root
# arguments should be
# $1 = interface
# $2 = writer port
# $3 = info port
# $4 = baseband dada key
/home/vlite-master/mtk/scripts/start_dada ${4} 257638400 32
/home/vlite-master/mtk/src/writer -e ${1} -p ${2} -i ${3} -k ${4} -o
# allow some time for buffer to empty before killing it
wait $(pgrep process_baseband)
sleep 1
/home/vlite-master/mtk/bin/dada_db -k ${4} -d
